### ISSUE TITLE
Short Dump STRING_OFFSET_TOO_LARGE

### ISSUE THREAD

**Issue by FFTad** [thedoginthewok/ZwdCSV#1]
Hi, 
I've been testing your class and it has been working very well. However, I had a few CSV files, that caused a short dump in the system. I was hoping, that you could check the csv file and try to parse it. The method used was parse_string. 

I'm attaching the file, where I've cut the 1.2Mio lines from the beginning to the last line, that was supposed to be parsed (header is still set as the first line in the file).

The error was:
 The offset (754) was greater than the current length of the string
 (753) however.
 Access is not possible like this.

the exporting table should have the following fields:

mandt  type mandt  
archiv_id  type saearchivi  
arc_doc_id  type saeardoid  
text  type string  
idx_last_mod_dat  type dats
herkunft_txt  type char3  

I'm curious what would the solution be.

BR,
Tadej

![image](https://user-images.githubusercontent.com/103022377/161747516-e20cd511-0082-4f62-91a7-c63628ed3648.png)

[hausmannstätten_test_1.csv](https://github.com/thedoginthewok/ZwdCSV/files/8417778/hausmannstatten_test_1.csv)

as you can see from the UltraEdit program, it seems that there is a new empty line in the last row and it it causing trouble:
![image](https://user-images.githubusercontent.com/103022377/161747799-e8a40517-8ff2-4f13-9d04-1d2cb604c739.png)

Do you think it's the file problem, or the program?

**Comment by WegnerDan** [comment]
I'm not quite sure what the problem is, I can't reproduce it. 
Can you post a code snippet of the call of the csv class constructor and method?

I wrote a little test report and parsed the file with it. I get the "too few columns" exception, but I think that's expected.

This is the output from the sample report:
![image](https://user-images.githubusercontent.com/6908247/162550112-5133eef0-7ec4-4911-a28e-c65f1fc24f34.png)

Column TEXT contains the following string:

> Marktgemeinde Hausmannstätten 
Marktplatz 1-2 
8888 Hausmannstätten 
TELEFON 03135/11111 FAX 03135/1111111-18 
E-MAIL gde@xxx. at 
Frau 
xxxxx Melanie 
Ulmenweg xxx 
8077 xxxxx 
DVR : 0000000 
StNr: 10423 ReNr: 4/282/1111 UID: A1U59448299 fällig: 21.11.11111 erstellt : 07.11.2016 
(L)ASTSCHRIFTSANZEIGE/ (R) ECHNUNG/ (B) ESCHEID im Sinne des § 11 Umsatzsteuergesetz Blatt : 1 
Position Verz .Nr Brutto Netto St . Cd/Steuer 
Zuslwusl Kursbeiträge (R) 282 -6,00 -6,00 0 0,00 
Korrektur Geb, Verz . 268 
STEIERM. SPARKASSE 
Marktgemeinde Hausmannstätten Marktgemeinde Hausmannstätten 
AT95xxxxxxxxxxxx 8 
STSPAT2GXXX STSPAT2GXXX 
StNr. : 111111/ReNr: 4/282/99999 
ReNr: 4/9999/2016 
Riemer Melanie 
StNr.: 1111111 
< 30+

Excel produces similar, if not the same result:
![image](https://user-images.githubusercontent.com/6908247/162550230-80d01806-877c-470a-a4dc-110565c4eabb.png)

This is the test report:
```abap
REPORT zwd_test_csv_issue_1.

TYPES:
  BEGIN OF ty_csv_line,
    mandt            TYPE mandt,
    archiv_id        TYPE saearchivi,
    arc_doc_id       TYPE saeardoid,
    text             TYPE string,
    idx_last_mod_dat TYPE dats,
    herkunft_txt     TYPE char3,
  END OF ty_csv_line,
  ty_csv_lines TYPE STANDARD TABLE OF ty_csv_line.
DATA:
  csv_lines TYPE ty_csv_lines.
TRY.
    NEW zcl_wd_csv_file( iv_endofline   = zcl_wd_csv=>mc_endofline_lf
                         iv_separator   = zcl_wd_csv=>mc_separator_comma
                         iv_delimiter   = zcl_wd_csv=>mc_delimiter_double_quote
                         iv_conv_exit   = abap_false
                         iv_trim_spaces = abap_false
    )->parse_file_local( EXPORTING iv_has_header = abap_true
                                   iv_path = 'C:\Users\thedo\Downloads\hausmannstatten_test_1.csv'
                         IMPORTING et_data = csv_lines ).
  CATCH zcx_wd_csv_invalid_endofline
        zcx_wd_csv_invalid_separator
        zcx_wd_csv_invalid_delimiter
        zcx_wd_csv_gui_upload_failed
        cx_sy_conversion_error
        cx_parameter_invalid_range
        cx_sy_codepage_converter_init
        cx_parameter_invalid_type
        cx_sy_struct_creation
        zcx_wd_csv_too_many_columns
        zcx_wd_csv_mixed_endofline INTO DATA(error).
    MESSAGE error TYPE 'S' DISPLAY LIKE 'E'.
  CATCH BEFORE UNWIND zcx_wd_csv_too_few_columns.
    RESUME.
ENDTRY.

BREAK-POINT.
```

**Comment by WegnerDan** [comment]
Closed because of inactivity
